[package]
name = "path-view"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17"
petgraph = "0.6"
postcard = "1"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1", features = ["full"] }
