[package]
name = "graph"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6"
rand = "0.8"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1", features = ["full"] }
