[package]
name = "graph"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17"
petgraph = { version = "0.6", features = ["serde-1"] }
postcard = "1"
rstar = "0.12"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1", features = ["full"] }
